# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/coursenotes/',
                'doc_host': 'https://muellerzr.github.io',
                'git_url': 'https://github.com/muellerzr/til/',
                'lib_path': 'coursenotes'},
  'syms': { 'coursenotes.nb_01': {},
            'coursenotes.nb_02': { 'coursenotes.nb_02.get_data': ('fully_connected.html#get_data', 'coursenotes/nb_02.py'),
                                   'coursenotes.nb_02.mse': ('fully_connected.html#mse', 'coursenotes/nb_02.py'),
                                   'coursenotes.nb_02.normalize': ('fully_connected.html#normalize', 'coursenotes/nb_02.py'),
                                   'coursenotes.nb_02.test_near_zero': ('fully_connected.html#test_near_zero', 'coursenotes/nb_02.py')},
            'coursenotes.nb_03': { 'coursenotes.nb_03.get_data': ('why_sqrt5.html#get_data', 'coursenotes/nb_03.py'),
                                   'coursenotes.nb_03.normalize': ('why_sqrt5.html#normalize', 'coursenotes/nb_03.py')}}}
