# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_data": "why_sqrt5.ipynb",
         "normalize": "why_sqrt5.ipynb",
         "test_near_zero": "fully_connected.ipynb",
         "mse": "fully_connected.ipynb",
         "MNIST_URL": "matmul.ipynb",
         "DATA_PATH": "why_sqrt5.ipynb"}

modules = ["nb_02.py",
           "nb_01.py",
           "nb_03.py"]

doc_url = "https://muellerzr.github.io/coursenotes/"

git_url = "https://github.com/muellerzr/coursenotes/tree/main/"

def custom_doc_links(name): return None
