# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/matmul.ipynb.

# %% auto 0
__all__ = ['MNIST_URL']

# %% ../nbs/matmul.ipynb 5
from pathlib import Path
from IPython.core.debugger import set_trace
import pickle, gzip, math, torch, matplotlib as mpl
import matplotlib.pyplot as plt
from torch import tensor
from fastcore.test import test_eq, test_close

from fastdownload import FastDownload

# %% ../nbs/matmul.ipynb 7
MNIST_URL = "https://figshare.com/ndownloader/files/25635053"
