# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/why_sqrt5.ipynb (unless otherwise specified).

__all__ = ['get_data', 'normalize', 'DATA_PATH']

# Cell
from pathlib import Path
import gzip, pickle
from torch import tensor
from functools import partial
import math

DATA_PATH = Path("../../../course-data")

def get_data():
    path = DATA_PATH/"mnist.pkl.gz"
    with gzip.open(path, 'rb') as f:
        ((x_train, y_train), (x_valid, y_valid), _) = pickle.load(f, encoding="latin-1")
    return map(tensor, (x_train,y_train,x_valid,y_valid))

def normalize(x, mean, std): return (x-mean)/std