# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/fully_connected.ipynb.

# %% auto 0
__all__ = ['get_data', 'normalize', 'test_near_zero', 'mse']

# %% ../nbs/fully_connected.ipynb 3
from .nb_01 import MNIST_URL
from fastdownload import FastDownload
import pickle, gzip
from torch import tensor
import torch, math
import matplotlib.pyplot as plt
from fastcore.test import test_close
from torch.nn import init

def get_data():
    fd = FastDownload(base="~/.fastai")
    path = fd.download(MNIST_URL)
    with gzip.open(path, 'rb') as f:
        ((x_train, y_train), (x_valid, y_valid), _) = pickle.load(f, encoding='latin-1')
    return map(tensor, (x_train,y_train,x_valid,y_valid))

def normalize(x, mean, std): return (x-mean)/std

# %% ../nbs/fully_connected.ipynb 8
def test_near_zero(a,tol=1e-3): assert a.abs()<tol, f"Near zero: {a}"

# %% ../nbs/fully_connected.ipynb 59
def mse(output, targ): return (output.squeeze(-1) - targ).pow(2).mean()

# %% ../nbs/fully_connected.ipynb 116
from torch import nn
