# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_data": "fully_connected.ipynb",
         "normalize": "fully_connected.ipynb",
         "test_near_zero": "fully_connected.ipynb",
         "MNIST_URL": "matmul.ipynb"}

modules = ["nb_02.py",
           "nb_01.py"]

doc_url = "https://muellerzr.github.io/notes/"

git_url = "https://github.com/muellerzr/notes/tree/main/"

def custom_doc_links(name): return None
