# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/fully_connected.ipynb (unless otherwise specified).

__all__ = ['get_data', 'normalize', 'test_near_zero']

# Cell
from .nb_01 import MNIST_URL
from fastdownload import FastDownload
import pickle, gzip
from torch import tensor
import torch, math
import matplotlib.pyplot as plt
from fastcore.test import test_close

def get_data():
    fd = FastDownload(base="~/.fastai")
    path = fd.download(MNIST_URL)
    with gzip.open(path, 'rb') as f:
        ((x_train, y_train), (x_valid, y_valid), _) = pickle.load(f, encoding='latin-1')
    return map(tensor, (x_train,y_train,x_valid,y_valid))

def normalize(x, mean, std): return (x-mean)/std

# Cell
def test_near_zero(a,tol=1e-3): assert a.abs()<tol, f"Near zero: {a}"